In [1]:
import torch

In [2]:
DTYPE = torch.float32

In [3]:
# gradient of Matrix multiplication

a_mat = 1*torch.ones(2,3, dtype=DTYPE)
b_mat = torch.arange(1,7, dtype=DTYPE).reshape(3,2)
a_mat, b_mat

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]))

In [4]:
a_mat = a_mat.clone().detach().requires_grad_(True)
b_mat = b_mat.clone().detach().requires_grad_(True)

In [5]:
c_mat = a_mat @ b_mat
c_mat

tensor([[ 9., 12.],
        [ 9., 12.]], grad_fn=<MmBackward0>)

In [6]:
loss = c_mat.sum()

In [7]:
loss.backward()

In [8]:
a_mat.grad, b_mat.grad

(tensor([[ 3.,  7., 11.],
         [ 3.,  7., 11.]]),
 tensor([[2., 2.],
         [2., 2.],
         [2., 2.]]))

In [ ]:
x_mat = 