In [1]:
import sys
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"
sys.path.append(".")
# os.environ["MAX_JOBS"] = "100"

import torch

In [2]:
from src.playg_v1.funcs import func, func2

INCLUDE: ['/system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include', '/system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/torch/csrc/api/include', '/system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/TH', '/system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/THC', '/system/apps/userenv/beck/xlstmpt21cu121/include']
/system/user/publicwork/beck/repos/xlstm/xlstm/models/vector_lstms/vkernels/cuda/src

/system/apps/userenv/beck/xlstmpt21cu121/lib


Using /system/user/beck/.cache/torch_extensions/py311_cu121 as PyTorch extensions root...
Creating extension directory /system/user/beck/.cache/torch_extensions/py311_cu121/playg_v2...
Detected CUDA files, patching ldflags
Emitting ninja build file /system/user/beck/.cache/torch_extensions/py311_cu121/playg_v2/build.ninja...
Building extension module playg_v2...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


[1/3] /system/apps/userenv/beck/xlstmpt21cu121/bin/x86_64-conda-linux-gnu-c++ -MMD -MF funcs.o.d -DTORCH_EXTENSION_NAME=playg_v2 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include -isystem /system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/TH -isystem /system/apps/userenv/beck/xlstmpt21cu121/lib/python3.11/site-packages/torch/include/THC -isystem /system/apps/userenv/beck/xlstmpt21cu121/include -isystem /system/apps/userenv/beck/xlstmpt21cu121/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /system/user/publicwork/beck/repos/xlstm/xlstm/models/vector_lstms/vkernels/cuda/src/playg_v1/funcs.cc -o funcs.o 
[2/3] /system/apps/userenv/beck/xlstmpt21cu1

RuntimeError: Error building extension 'playg_v2'

In [3]:
DTYPE = torch.bfloat16
DEVICE = torch.device("cuda:0")

In [4]:
mat_A = torch.arange(4).reshape(2, 2).to(dtype=DTYPE, device=DEVICE)
mat_A

tensor([[0., 1.],
        [2., 3.]], device='cuda:0', dtype=torch.bfloat16)

In [5]:
out = func(mat_A)
out

Test kernel!


tensor([[0., 1.],
        [2., 3.]], device='cuda:0', dtype=torch.bfloat16)

In [6]:
out = func2(mat_A)
out 

before kernel dispatch!
rows: 2, cols: 2
blocksxy: 1-1, threads: 32-32


tensor([[0., 1.],
        [2., 3.]], device='cuda:0', dtype=torch.bfloat16)