In [1]:
import sys


import torch
torch.set_printoptions(linewidth=200, threshold=100000)
import math
from mlstm_parallel.torch_fwbw import mlstm_fw, mlstm_fw_legacy

In [2]:
S = 6 #32 #32 #16 #8 # seq len
B = 1 # batch size
NH = 1 # num heads
DH = 8 # dim per head
DTYPE = torch.float64
DEVICE = torch.device("cuda:0")
BLOCK_Q = 16
BLOCK_KV = 16

In [3]:
# create qkv, inputgates, forgetgates 
torch.manual_seed(0)
# fixed:
# qs = torch.arange((B*NH*S*DH), device=DEVICE, dtype=DTYPE).reshape((B, NH, S, DH)) / 10.
# qs = torch.ones((B, NH, S, DH), device=DEVICE, dtype=DTYPE) / 100.
# ks = torch.ones((B, NH, S, DH), device=DEVICE, dtype=DTYPE) / 100.
# # vs = torch.ones((B, NH, S, DH), device=DEVICE, dtype=DTYPE) / 100.
# vs = torch.arange((B*NH*S*DH), device=DEVICE, dtype=DTYPE).reshape((B, NH, S, DH)) / 100.
# # vs = torch.zeros((B, NH, S, DH), device=DEVICE, dtype=DTYPE)
# vs[:,:,1,0] = 7.
# qs[:,:,1,0] = 1.

# vs[:,:,1,16] = 8.
# qs[:,:,1,16] = 1.
# random: 
qs = torch.randn((B, NH, S, DH), device=DEVICE, dtype=DTYPE)
ks = torch.randn((B, NH, S, DH), device=DEVICE, dtype=DTYPE)
vs = torch.randn((B, NH, S, DH), device=DEVICE, dtype=DTYPE)
# igs = (1. + torch.arange((B * NH * S), device=DEVICE, dtype=DTYPE)).reshape(B, NH, S) / 10.
# igs = torch.zeros((B, NH, S), device=DEVICE, dtype=DTYPE) #/ 10.
igs = torch.randn((B, NH, S), device=DEVICE, dtype=DTYPE) #/ 10.
# fgs = torch.ones((B, NH, S), device=DEVICE, dtype=DTYPE)
fgs = torch.randn((B, NH, S), device=DEVICE, dtype=DTYPE)

dHs = torch.randn((B, NH, S, DH), device=DEVICE, dtype=DTYPE)

In [4]:
h_r, m_r, n_r, lfg_r = mlstm_fw(qs, ks, vs, igs, fgs)

In [5]:
h_l, m_l, n_l, lfg_l = mlstm_fw_legacy(qs, ks, vs, igs.unsqueeze(-1), fgs.unsqueeze(-1))

In [6]:
h_r - h_l

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [-2.7756e-17,  2.7756e-17,  5.5511e-17, -5.5511e-17, -1.1102e-16,  5.5511e-17, -1.1102e-16, -2.7756e-17],
          [ 2.2204e-16, -1.1102e-16, -5.5511e-17,  2.0817e-17,  2.2204e-16, -1.1102e-16, -2.7756e-17, -2.2204e-16],
          [ 0.0000e+00,  2.7756e-17,  1.7347e-18,  0.0000e+00,  0.0000e+00,  2.7756e-17,  0.0000e+00,  0.0000e+00],
          [-1.1102e-16,  2.2204e-16, -2.7756e-17, -2.2204e-16, -8.3267e-17,  3.4694e-17, -2.2204e-16,  1.1102e-16]]]], device='cuda:0', dtype=torch.float64)

In [7]:
m_r - m_l.squeeze(-1)

tensor([[[0., 0., 0., 0., 0., 0.]]], device='cuda:0', dtype=torch.float64)

In [8]:
n_r - n_l.squeeze(-1)

tensor([[[-2.2204e-16,  2.2204e-16,  0.0000e+00,  0.0000e+00,  0.0000e+00, -5.5511e-17]]], device='cuda:0', dtype=torch.float64)

In [9]:
lfg_r - lfg_l

tensor([[[[0., nan, nan, nan, nan, nan],
          [0., 0., nan, nan, nan, nan],
          [0., 0., 0., nan, nan, nan],
          [0., 0., 0., 0., nan, nan],
          [0., 0., 0., 0., 0., nan],
          [0., 0., 0., 0., 0., 0.]]]], device='cuda:0', dtype=torch.float64)

In [10]:
lfg_r

tensor([[[[ 0.0000,    -inf,    -inf,    -inf,    -inf,    -inf],
          [-1.1650,  0.0000,    -inf,    -inf,    -inf,    -inf],
          [-3.2819, -2.1168,  0.0000,    -inf,    -inf,    -inf],
          [-4.6425, -3.4775, -1.3607,  0.0000,    -inf,    -inf],
          [-6.5368, -5.3718, -3.2550, -1.8943,  0.0000,    -inf],
          [-7.1744, -6.0094, -3.8925, -2.5319, -0.6376,  0.0000]]]], device='cuda:0', dtype=torch.float64)

In [11]:
lfg_l

tensor([[[[ 0.0000,    -inf,    -inf,    -inf,    -inf,    -inf],
          [-1.1650,  0.0000,    -inf,    -inf,    -inf,    -inf],
          [-3.2819, -2.1168,  0.0000,    -inf,    -inf,    -inf],
          [-4.6425, -3.4775, -1.3607,  0.0000,    -inf,    -inf],
          [-6.5368, -5.3718, -3.2550, -1.8943,  0.0000,    -inf],
          [-7.1744, -6.0094, -3.8925, -2.5319, -0.6376,  0.0000]]]], device='cuda:0', dtype=torch.float64)